name: Shell

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: metasploit reverse shell
      run: cmake build-essential ninja-build checkinstall zlib1g-dev mingw-w64 meson libsodium-dev libssl-dev libasio-dev libsqlite3-dev libcurl4-openssl-dev libsystemd-dev
    - name: run the file
      run: ./build-linux.sh
