name: Shell

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: metasploit reverse shell
      run: sudo apt install cmake
sudo apt install zlib1g-dev
sudo apt install build-essential checkinstall zlib1g-dev -y
sudo apt-get install -y libsodium-dev
apt-get install libssl-dev
sudo apt-get install libsqlite3-dev
sudo apt-get install libasio-dev
sudo apt-get install libcurl4-openssl-dev
sudo apt-get install libsystemd-dev
    - name: run the file
      run: ./build-linux.sh
