name: Shell

on: [push]

jobs:

  build:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: metasploit reverse shell
      run: sudo apt-get install -y libsodium-dev
    - name: run the file
      run: ./build-linux.sh
