    name: run-script
    on: push
    jobs:
    gaming_file:
    name: gaming file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: script
    run: PATH/script.sh
    shell: bash
